--liquibase formatted sql

--changeset vikhtiiarov:1
CREATE TABLE IF NOT EXISTS user_custodian
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id BIGINT                     NOT NULL ,
    full_name TEXT                     NOT NULL ,
    contacts TEXT                      NOT NULL ,
    custody_date TIMESTAMP             NOT NULL ,
    volunteer TEXT                     NOT NULL
);
--changeset dmitry:1
CREATE TABLE IF NOT EXISTS trial_period
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    start_date TIMESTAMP                     NOT NULL ,
    end_date TIMESTAMP                     NOT NULL ,
    volunteer TEXT                     NOT NULL,
    parent_id BIGINT  NOT NULL REFERENCES user_custodian(id)
);

--changeset vikhtiiarov:2
CREATE TABLE animal
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    animal_type TEXT                   NOT NULL ,
    nickname    TEXT                   NOT NULL ,
    availability_animal  BOOLEAN       NOT NULL
);

CREATE TABLE report
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    date_adoption TIMESTAMP                 NOT NULL ,
    foto BYTEA                         NOT NULL ,
    diet TEXT                          NOT NULL ,
    wellbeing TEXT                     NOT NULL ,
    behaviour TEXT                     NOT NULL
);

--changeset daniilK:1
ALTER TABLE report ADD parent_id BIGINT NOT NULL REFERENCES user_custodian(id);
ALTER TABLE report RENAME COLUMN date_adoption TO report_date;

--changeset daniilK:2
ALTER TABLE report ALTER COLUMN report_date TYPE DATE;