--liquibase formatted sql

--changeset vikhtiiarov:1
CREATE TABLE IF NOT EXISTS user_custodian
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id BIGINT                     NOT NULL ,
    full_name TEXT                     NOT NULL ,
    contacts TEXT                      NOT NULL ,
    custody_date TIMESTAMP             NOT NULL ,
    volunteer TEXT                     NOT NULL
);

--changeset vikhtiiarov:2
CREATE TABLE animal
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    animal_type TEXT                   NOT NULL ,
    nickname    TEXT                   NOT NULL ,
    availability_animal  BOOLEAN       NOT NULL
);

CREATE TABLE report
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    date_adoption DATE                 NOT NULL ,
    foto BLOB                          NOT NULL ,
    diet TEXT                          NOT NULL ,
    wellbeing TEXT                     NOT NULL ,
    behaviour TEXT                     NOT NULL
);